name: Build
on:
  push:
    branches: [ master ]

env:
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Login to Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@1814d3dfb36d6f84174e61f4a4b05bd84089a4b9
        with:
          context: .
          tags: ${{ secrets.REGISTRY_URL }}/jit-evolution:latest
          push: true
  deploy:
    needs: ["build"]
    runs-on: ubuntu-latest
    
    steps:
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: docker-compose -f ~/jit-evolution/docker-compose.yml pull && ./jit-evolution/migrate.sh && docker-compose -f ~/jit-evolution/docker-compose.yml up -d
        script_stop: true
